// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIhn1ovsH035VdsSvS5KspyPmI8pgmg2Q',
    appId: '1:927366578228:web:4ebf2cbf5c18861e0e4a61',
    messagingSenderId: '927366578228',
    projectId: 'monumental-habits-31e09',
    authDomain: 'monumental-habits-31e09.firebaseapp.com',
    storageBucket: 'monumental-habits-31e09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6ccIlXMw5qL61dP5AiB_CmTX_lglwfc',
    appId: '1:927366578228:android:45668785b2f948d30e4a61',
    messagingSenderId: '927366578228',
    projectId: 'monumental-habits-31e09',
    storageBucket: 'monumental-habits-31e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThjHhXAfCTUxK2KGqJaaXzKXYigeEsjo',
    appId: '1:927366578228:ios:5dd6aabc80c0d4690e4a61',
    messagingSenderId: '927366578228',
    projectId: 'monumental-habits-31e09',
    storageBucket: 'monumental-habits-31e09.appspot.com',
    iosBundleId: 'com.example.monumentalHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThjHhXAfCTUxK2KGqJaaXzKXYigeEsjo',
    appId: '1:927366578228:ios:5dd6aabc80c0d4690e4a61',
    messagingSenderId: '927366578228',
    projectId: 'monumental-habits-31e09',
    storageBucket: 'monumental-habits-31e09.appspot.com',
    iosBundleId: 'com.example.monumentalHabits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIhn1ovsH035VdsSvS5KspyPmI8pgmg2Q',
    appId: '1:927366578228:web:797393ab493b5fec0e4a61',
    messagingSenderId: '927366578228',
    projectId: 'monumental-habits-31e09',
    authDomain: 'monumental-habits-31e09.firebaseapp.com',
    storageBucket: 'monumental-habits-31e09.appspot.com',
  );
}
